import { Link } from 'react-router-dom'
import { ShoppingBag } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { PageHero } from '@/components/layout/PageHero'
import { useCartStore } from '@/store/cartStore'

export function CartPage() {
  const { items, subtotal, shipping, total, updateQuantity, removeItem } = useCartStore()
  return <><PageHero eyebrow="Your bag" title={items.length ? 'Ready when you are.' : 'Your bag is waiting.'} description={items.length ? 'Review your handmade finds before checkout.' : 'Discover a small handmade piece that feels just right.'} /><section className="bg-[#F6EFE7] px-5 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl">{!items.length ? <div className="rounded-2xl border border-[#E7DDD5] bg-white px-6 py-14 text-center"><ShoppingBag className="mx-auto mb-4 text-[#B56A45]" size={30} /><h2 className="font-[Playfair_Display] text-2xl font-bold text-[#46352A]">Nothing here yet</h2><p className="mx-auto mt-2 max-w-sm text-sm text-[#786A61]">Your bag is the perfect place for a forever flower or a thoughtful little gift.</p><Link to="/#categories" className="mt-6 inline-flex"><Button>Explore the collection</Button></Link></div> : <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-3">{items.map((item) => <article key={`${item.product.id}-${item.selected_color?.name ?? ''}`} className="flex gap-4 rounded-2xl border border-[#E7DDD5] bg-white p-4"><div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl bg-[#F6EFE7] text-3xl">🌸</div><div className="min-w-0 flex-1"><p className="font-[Playfair_Display] font-bold text-[#46352A]">{item.product.name}</p><p className="mt-1 text-sm font-semibold text-[#B56A45]">₹{item.product.price}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center rounded-lg border border-[#E7DDD5]"><button onClick={() => updateQuantity(item.product.id, item.quantity - 1)} className="px-3 py-1.5 text-[#786A61]">−</button><span className="px-2 text-sm font-semibold">{item.quantity}</span><button onClick={() => updateQuantity(item.product.id, item.quantity + 1)} className="px-3 py-1.5 text-[#786A61]">+</button></div><button onClick={() => removeItem(item.product.id)} className="text-xs font-semibold text-[#B56A45] hover:underline">Remove</button></div></div></article>)}</div><aside className="h-fit rounded-2xl bg-[#46352A] p-6 text-[#FFF9F2]"><h2 className="font-[Playfair_Display] text-xl font-bold">Order summary</h2><div className="mt-5 space-y-3 text-sm text-[#EDE3DA]"><p className="flex justify-between"><span>Subtotal</span><span>₹{subtotal()}</span></p><p className="flex justify-between"><span>Shipping</span><span>{shipping() ? `₹${shipping()}` : 'Free'}</span></p><p className="flex justify-between border-t border-white/15 pt-3 font-semibold text-white"><span>Total</span><span>₹{total()}</span></p></div><Link to="/checkout" className="mt-6 block"><Button className="w-full" variant="primary">Continue to checkout</Button></Link></aside></div>}</div></section></>
}
